# Generated by Django 3.1.4 on 2020-12-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
