# Generated by Django 3.1.4 on 2020-12-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201221_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode_ext',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
